#!/usr/bin/env python3
"""Check the atlas against ms1-dup's numbers of record. The FIRST check that looks outward.

WHY. Every other check in this repo compares the atlas against itself. `check_aggregates.py`
recomputes each manifest summary from the shards; `check_prose_numbers.py` recomputes the About
page's sentences from the shards; `validate_data.py` checks internal consistency. All of them
pass while the atlas is uniformly, confidently wrong -- which is exactly what happened when the
LSG pool was withdrawn upstream and this site served the withdrawn figure for four days with
every check green (see docs/HANDOFF.md, and the 1,725-vs-1,611 home page for two releases).

A repo cannot notice its own staleness by looking inward. So this check reads the OWNING
analysis's published numbers -- ms1-dup's FACTS_v10.json, generated by `build_facts_v10.py`
-- and recomputes the same quantities from the committed shards.

PINNED, NOT VENDORED. This repo's root is published by GitHub Pages, so a copy of FACTS here
would be public, and it carries values that are held off the site (tau, and the v10 figures
while the atlas is held on v9). `sources/facts_v10.pin.json` records only the ms1-dup commit
and the sha256. The bytes are read with `git show <commit>:<path>`, so they are the pinned
bytes whatever the ms1-dup checkout currently has checked out -- a stale clone cannot feed
this check the wrong file, which is the failure the 2026-09-20 contract audit kept finding.

THE SHARDS ARE THE ARTIFACT. Everything in data/meta/manifest.json is a summary of them and is
stale by default. So facts are recomputed from data/genes/**, and the manifest is then checked
as a SEPARATE claim: a manifest that disagrees with its own shards is its own defect.

DECLARED VERSION, not a blanket skip. The atlas is deliberately on duplication v9 while ms1-dup
has moved to v10 (Chen's hold, 2026-09-20). The weak response would be "skip duplication".
Instead DECLARED_BASIS names v9 and every duplication fact is checked against its v9 counterpart
-- so "the atlas is coherently on v9" is asserted on every code and every count, and a drift off
v9 fails just as loudly as a drift off v10. A divergence is only acceptable when it is DECLARED
here with a reason; anything else fails.
"""
import glob
import hashlib
import json
import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, "data")
PIN = os.path.join(ROOT, "sources", "facts_v10.pin.json")

# Where ms1-dup lives on this machine. Same order as ms1-dup's own atlas_contract roots:
# an explicit env var, then the two conventional layouts.
MS1_CANDIDATES = [os.environ.get("MS1_DUP_ROOT", ""),
                  os.path.expanduser("~/dev/ms1-dup"),
                  f"/scratch/{os.environ.get('USER', '')}/ms1-dup"]

HAPS = {"hap1": "HAP1", "hap2": "HAP2"}
HEMI = {"hemizygous_HAP1", "hemizygous_HAP2"}

# The duplication version this atlas's `dup` layer is built on. The shards carry no version
# marker of their own -- a gap worth closing when that layer is next built -- so it is declared
# here and then VERIFIED below rather than trusted.
DECLARED_BASIS = "v10"

# atlas quantity -> the FACTS key it must equal, given DECLARED_BASIS.
BASIS_MAP = {
    "v9": {"swgd": "swgd_genes_v9", "awgd": "awgd_genes_v9", "letter": "dup_type_v9"},
    "v10": {"swgd": "swgd_genes", "awgd": "awgd_genes", "letter": "dup_type_v10"},
}

# Divergences that are known, deliberate and explained. Anything NOT listed here fails.
# Keep the reason and the date: an entry with no reason is how a defect becomes permanent.
# 2026-10-03: the atlas moved to the current per-gene table (dup_type_v10 letters and anchors,
# strict PAV, relationship categories) at Chen's decision, so there is no declared divergence.
DECLARED_DIVERGENCES = {}
CATEGORY_PIN = os.path.join(ROOT, "sources", "syntelog_categories.pin.json")
CATEGORY_FACTS = {   # shard rel.c code -> the owning analysis's fact key
    "1:1": "cj_1to1_genes", "N:N_TD": "cj_NN_TD_genes", "N:N_nonTD": "cj_NN_nonTD_genes",
    "CNV_TD": "cj_CNV_TD_genes", "CNV_nonTD": "cj_CNV_nonTD_genes",
    "hemizygous_strict_PAV": "cj_hemizygous_strict_PAV_genes",
    "hemizygous_TD_array": "cj_hemizygous_TD_array_genes",
    "hemizygous_nonPAV": "cj_hemizygous_nonPAV_genes",
}

fails, notes = [], []


def check(name, ok, detail=""):
    print(f"  {'PASS' if ok else 'FAIL'}  {name}" + (f"  -- {detail}" if detail else ""))
    if not ok:
        fails.append(name)


def shard_paths(hap):
    """Per-chromosome shards live in subdirectories; scaffolds sit beside them as a single
    file. Globbing only `*/*.json` silently drops 131 HAP1 genes and makes three letter-code
    counts look wrong -- measured, 2026-09-20."""
    return (sorted(glob.glob(os.path.join(DATA, "genes", hap, "*", "*.json")))
            + sorted(glob.glob(os.path.join(DATA, "genes", hap, "*.json"))))


def measure():
    """Recompute every checkable quantity from the committed shards."""
    m = {k: {"HAP1": 0, "HAP2": 0} for k in
         ("genes", "swgd", "awgd", "tandem", "pav_strict")}
    m.update({c: {"HAP1": 0, "HAP2": 0} for c in CATEGORY_FACTS})
    letter = {"HAP1": {}, "HAP2": {}}
    for hap, H in HAPS.items():
        for path in shard_paths(hap):
            for _gid, r in json.load(open(path)).items():
                m["genes"][H] += 1
                d = r.get("dup") or {}
                if d.get("t"):
                    letter[H][d["t"]] = letter[H].get(d["t"], 0) + 1
                for key, fld in (("swgd", "s"), ("awgd", "a"), ("tandem", "td")):
                    if d.get(fld):
                        m[key][H] += 1
                if (r.get("pav") or {}).get("strict"):
                    m["pav_strict"][H] += 1
                c = (r.get("rel") or {}).get("c")
                if c:
                    m[c][H] += 1
    return m, letter


def load_pinned_facts():
    """Read FACTS_v10.json at the PINNED commit, through git, and verify its sha256.

    Returns (doc, detail) or (None, reason). Never falls back to a working-tree file: a working
    tree can be on any branch, and reading it would re-open exactly the stale-checkout hole this
    project spent a day closing. If the commit object is absent, git show fails and so do we --
    the answer is to fetch, which is safe here because we read a COMMIT, not HEAD.
    """
    if not os.path.exists(PIN):
        return None, f"{os.path.relpath(PIN, ROOT)} is missing"
    pin = json.load(open(PIN))
    roots = [r for r in MS1_CANDIDATES if r and os.path.isdir(r)]
    if not roots:
        return None, ("no ms1-dup checkout found (set MS1_DUP_ROOT). This check needs one, "
                      "like the rest of build_all.sh's two-machine build; it does not skip")
    for root in roots:
        res = subprocess.run(
            ["git", "-C", root, "show", f"{pin['ms1_dup_commit']}:{pin['source_path']}"],
            capture_output=True)
        if res.returncode != 0:
            continue
        got = hashlib.sha256(res.stdout).hexdigest()
        if got != pin["sha256"]:
            return None, (f"{root} at {pin['ms1_dup_commit'][:9]} gives sha256 {got[:16]}, "
                          f"pin says {pin['sha256'][:16]} -- the pin and the commit disagree")
        return json.loads(res.stdout), f"{root} @ {pin['ms1_dup_commit'][:9]}, sha256 verified"
    return None, (f"none of {roots} contains commit {pin['ms1_dup_commit'][:9]}. "
                  f"`git -C <ms1-dup> fetch` and re-run")


class MissingFact(Exception):
    pass


def want(facts, key):
    """A fact this check needs. Missing is a hard, NAMED failure, not a bare KeyError.

    Real case: the v9 anchor facts were added on an ms1-dup branch before they reached main, so
    `refresh_facts.sh` with its default ref (origin/main) would move the pin to a file that
    does not have them. That must fail saying so, not crash with a traceback.
    """
    if key not in facts:
        raise MissingFact(key)
    return facts[key]["value"]


def cmp_hap(name, got, facts, key, extra=""):
    w = want(facts, key)
    ok = got["HAP1"] == w["HAP1"] and got["HAP2"] == w["HAP2"]
    check(name, ok, f"atlas {got['HAP1']:,}/{got['HAP2']:,} vs {key} "
                    f"{w['HAP1']:,}/{w['HAP2']:,}{extra}")
    return ok


def main():
    doc, how = load_pinned_facts()
    if doc is None:
        # FAIL, not skip: "could not run" is not "passed".
        print(f"  FAIL  read the pinned numbers of record  -- {how}")
        print("\n1 CHECK(S) FAILED: ['read the pinned numbers of record']")
        return 1
    facts = doc["facts"]
    print(f"== numbers of record: {doc['schema']} {doc['version']}, {len(facts)} facts ==")
    check("read the pinned numbers of record", True, how)

    m, letter = measure()
    basis = BASIS_MAP[DECLARED_BASIS]
    print(f"\n== recomputed from the shards ({sum(m['genes'].values()):,} genes) ==")

    cmp_hap("gene count", m["genes"], facts, "genes_total")
    cmp_hap("tandem genes", m["tandem"], facts, "tandem_genes")

    print(f"\n== duplication, against the DECLARED basis ({DECLARED_BASIS}) ==")
    coherent = True
    coherent &= cmp_hap(f"sWGD genes match {DECLARED_BASIS}", m["swgd"], facts, basis["swgd"])
    coherent &= cmp_hap(f"aWGD genes match {DECLARED_BASIS}", m["awgd"], facts, basis["awgd"])

    lw = want(facts, basis["letter"])
    codes = sorted(set(letter["HAP1"]) | set(letter["HAP2"]) | set(lw))
    bad = [c for c in codes
           if letter["HAP1"].get(c, 0) + letter["HAP2"].get(c, 0) != lw.get(c, {}).get("total", 0)]
    coherent &= not bad
    check(f"every letter code matches {basis['letter']}", not bad,
          f"{len(codes)} codes" + (f", differing: {bad}" if bad else ", all equal"))

    # A declared divergence only excuses the version. It does NOT excuse incoherence: if the
    # atlas matches neither v9 nor v10, "we are on v9" was not true and the entry is cover.
    if not coherent:
        other = "v10" if DECLARED_BASIS == "v9" else "v9"
        ob = BASIS_MAP[other]
        alt = (m["swgd"]["HAP1"] == want(facts, ob["swgd"])["HAP1"]
               and m["awgd"]["HAP1"] == want(facts, ob["awgd"])["HAP1"])
        notes.append(f"the atlas matches neither {DECLARED_BASIS} nor {other} on duplication"
                     if not alt else
                     f"the atlas actually matches {other}; DECLARED_BASIS says {DECLARED_BASIS}")

    print("\n== relationship categories and strict PAV, against the category facts ==")
    cpin = json.load(open(CATEGORY_PIN))
    for root in [r for r in MS1_CANDIDATES if r and os.path.isdir(r)]:
        res = subprocess.run(["git", "-C", root, "show",
                              f"{cpin['ms1_dup_commit']}:{cpin['files']['facts']['path']}"], capture_output=True)
        if res.returncode == 0:
            break
    ok = res.returncode == 0 and hashlib.sha256(res.stdout).hexdigest() == cpin["files"]["facts"]["sha256"]
    check("read the pinned category facts", ok, cpin["files"]["facts"]["path"])
    if ok:
        cf = json.loads(res.stdout)["facts"]
        for code, key in CATEGORY_FACTS.items():
            cmp_hap(f"category {code}", m[code], cf, key)
        cmp_hap("strict PAV genes (the dissertation's set)", m["pav_strict"], cf,
                "cj_hemizygous_strict_PAV_genes")

    # The manifest is a summary of the shards and stale by default. Check it separately: the
    # rendered pages read it, so a manifest that disagrees with its own shards is its own bug.
    print("\n== the manifest's own claims, against the shards it summarises ==")
    man = json.load(open(os.path.join(DATA, "meta", "manifest.json")))
    pav = man.get("pav") or {}
    for h, H in (("hap1", "HAP1"), ("hap2", "HAP2")):
        k = f"strict_{h}"
        check(f"manifest.pav.{k} matches the shards", pav.get(k) == m["pav_strict"][H],
              f"manifest {pav.get(k)} vs shards {m['pav_strict'][H]:,}")

    print("\n== declared divergences ==")
    for k, why in DECLARED_DIVERGENCES.items():
        print(f"  DECLARED  {k}\n            {why}")

    print()
    for n in notes:
        print(f"  !! {n}")
    if fails:
        print(f"\n{len(fails)} CHECK(S) FAILED: {fails}")
        print("\nA failure here means the atlas and the owning analysis disagree. Either the")
        print("atlas needs rebuilding, or the divergence is deliberate and belongs in")
        print("DECLARED_DIVERGENCES with a reason and a date.")
        return 1
    print("ATLAS AGREES WITH THE NUMBERS OF RECORD")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except MissingFact as e:
        print(f"\n  FAIL  the pinned facts file has no '{e.args[0]}'")
        print("        The pin points at a FACTS_v10.json older than this check. Move the pin")
        print("        (scripts/refresh_facts.sh <ref>) to a commit that carries it.")
        print("\n1 CHECK(S) FAILED: ['pinned facts carry every fact this check needs']")
        sys.exit(1)
